export const POKEMON_TYPES = {
  bug: {
    backgroundColor: '#E3D985',
    fontColor: '#000000'
  } ,
  dark: {
    backgroundColor: '#50514F',
    fontColor: '#FFFFFF'
  } ,
  dragon: {
    backgroundColor: '#574AE2',
    fontColor: '#FFFFFF'
  } ,
  eletric: {
    backgroundColor: '#F7B32B',
    fontColor: '#000000'
  } ,
  fairy: {
    backgroundColor: '#FF8CC6',
    fontColor: '#000000'
  } ,
  fighting: {
    backgroundColor: '#481D24',
    fontColor: '#FFFFFF'
  } ,
  fire: {
    backgroundColor: '#F72C25',
    fontColor: '#FFFFFF'
  } ,
  flying: {
    backgroundColor: '#8093F1',
    fontColor: '#FFFFFF'
  } ,
  ghost: {
    backgroundColor: '#19297C',
    fontColor: '#FFFFFF'
  } ,
  grass: {
    backgroundColor: '#69B578',
    fontColor: '#FFFFFF'
  } ,
  ground: {
    backgroundColor: '#FCF6B1',
    fontColor: '#000000'
  } ,
  ice: {
    backgroundColor: '#77B6EA',
    fontColor: '#000000'
  } ,
  normal: {
    backgroundColor: '#E8EEF2',
    fontColor: '#000000'
  } ,
  poison: {
    backgroundColor: '#654597',
    fontColor: '#FFFFFF'
  } ,
  psychic: {
    backgroundColor: '#D44D5C',
    fontColor: '#FFFFFF'
  } ,
  rock: {
    backgroundColor: '#D5BF86',
    fontColor: '#000000'
  } ,
  shadow: {
    backgroundColor: '#102542',
    fontColor: '#FFFFFF'
  } ,
  steel: {
    backgroundColor: '#F4EBE8',
    fontColor: '#000000'
  } ,
  unknown: {
    backgroundColor: '#68B0AB',
    fontColor: '#FFFFFF'
  } ,
  water: {
    backgroundColor: '#3993DD',
    fontColor: '#FFFFFF '
  } ,
  
}