export const POKEMON_MAX_STATS = {
  HP: 255,
  attack: 190,
  defence: 250,
  specialAttack: 194,
  specialDefence: 250,
  speed: 200
}

export const POKEMON_TYPES = {
  bug: {
    backgroundColor: '#92BC2C',
    fontColor: '#FFFFFF'
  } ,
  dark: {
    backgroundColor: '#595761',
    fontColor: '#FFFFFF'
  } ,
  dragon: {
    backgroundColor: '#0C69C8',
    fontColor: '#FFFFFF'
  } ,
  electric: {
    backgroundColor: '#F7B32B',
    fontColor: '#FFFFFF'
  } ,
  fairy: {
    backgroundColor: '#EE90E6',
    fontColor: '#FFFFFF'
  } ,
  fighting: {
    backgroundColor: '#481D24',
    fontColor: '#FFFFFF'
  } ,
  fire: {
    backgroundColor: '#D3425F',
    fontColor: '#FFFFFF'
  } ,
  flying: {
    backgroundColor: '#A1BBEC',
    fontColor: '#FFFFFF'
  } ,
  ghost: {
    backgroundColor: '#5F6DBC',
    fontColor: '#FFFFFF'
  } ,
  grass: {
    backgroundColor: '#69B578',
    fontColor: '#FFFFFF'
  } ,
  ground: {
    backgroundColor: '#DA7C4D',
    fontColor: '#FFFFFF'
  } ,
  ice: {
    backgroundColor: '#75D0C1',
    fontColor: '#FFFFFF'
  } ,
  normal: {
    backgroundColor: '#A0A29F',
    fontColor: '#FFFFFF'
  } ,
  poison: {
    backgroundColor: '#654597',
    fontColor: '#FFFFFF'
  } ,
  psychic: {
    backgroundColor: '#D44D5C',
    fontColor: '#FFFFFF'
  } ,
  rock: {
    backgroundColor: '#D5BF86',
    fontColor: '#FFFFFF'
  } ,
  shadow: {
    backgroundColor: '#102542',
    fontColor: '#FFFFFF'
  } ,
  steel: {
    backgroundColor: '#5695A3',
    fontColor: '#FFFFFF'
  } ,
  unknown: {
    backgroundColor: '#68B0AB',
    fontColor: '#FFFFFF'
  } ,
  water: {
    backgroundColor: '#3993DD',
    fontColor: '#FFFFFF '
  } ,
  
}